<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>PptChartRoundtripTest</RootNamespace>
    <AssemblyName>PptChartRoundtripTest</AssemblyName>
    <LangVersion>8.0</LangVersion>
    <Nullable>disable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <UseWindowsForms>true</UseWindowsForms>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <PropertyGroup>
    <OfficePiaDir>C:\Program Files (x86)\Microsoft Visual Studio\Shared\Visual Studio Tools for Office\PIA\Office15</OfficePiaDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\EasyWriteClient.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Microsoft.Office.Interop.PowerPoint">
      <HintPath>$(OfficePiaDir)\Microsoft.Office.Interop.PowerPoint.dll</HintPath>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="Office">
      <HintPath>$(OfficePiaDir)\Office.dll</HintPath>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
